# File: flutter_logger/pubspec.yaml

name: geek_flutter_util
description: A reusable flutter util for geek project
version: 1.0.0
homepage: https://github.com/geekgeekgo-io/geek_flutter_util

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter